@Deploy_HostAddress = http://localhost:5215

GET {{Deploy_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{Deploy_HostAddress}}/api/v1/tts/generate
Content-Type: application/json

{
  "text": "Hello from the TTS cache API.",
  "voiceId": "RaFzMbMIfqBcIurH6XF9",
  "modelId": "eleven_multilingual_v2"
}

###

GET {{Deploy_HostAddress}}/api/v1/tts/audio/<textHash>

###
